import Whatwg.Html.Schema

/-!
# Whatwg.Html.Content.Lattice

The inclusion and separation lemmas over the generated content sets (node L1
and node L2 of the H3 proof graph in `docs/HTML-PACKAGE-PLAN.md`, ruling
HP-6), together with the finite-enumeration infrastructure every later
content-model proof reuses.

Route. `Tag` and `ContentSet` are finite enumerations and every membership
function generated by slice H2 is constructor dispatch, so a universally
quantified statement over tags is decided by one `List.all` over `Tag.all`
and one appeal to `Tag.mem_all`. `forall_tag_of_all` below is that appeal;
every lemma in this module is `... (by decide +kernel)` through it. No tactic outside
the ceiling of `Whatwg/AGENTS.md` appears here.

What the boolean decompositions are for. TyXML writes each `x_without_y`
content set as its own explicit inclusion list rather than as a subtraction
from `x`, so the name of a set is not evidence about its members. This module
therefore computes the actual difference `x \ x_without_y` from the generated
data, names it as an exclusion predicate under `Excluded`, and states the
decomposition `x_without_y t = (x t && !excluded t)` as a theorem. Where the
difference is not what the family name suggests, the theorem is true to the
data and its docstring lists the exact tags. The observed departures at this
pin are:

- `core_flow5_without_media`, `core_flow5_without_noscript`,
  `core_phrasing_without_media` and `core_phrasing_without_noscript` exclude
  nothing at all: each is equal to its base as a membership function.
- `phrasing_without_noscript` is not `phrasing` minus `noscript`. TyXML
  defines it as the transparent row alone, so it has 11 members and is equal
  to `transparent_without_noscript`; 44 of the 55 members of `phrasing` are
  absent from it.
- `core_phrasing_without_noscript` is consequently *not* inside
  `phrasing_without_noscript`: the two sets are disjoint.
- `phrasing_without_dfn`, `phrasing_without_label`, `phrasing_without_meter`,
  `phrasing_without_progress` and `phrasing_without_time` each drop `Embed`,
  `Iframe` and `Svg` in addition to the tag their name mentions.
- `flow5_without_interactive` drops `Details`, `Embed`, `Iframe` and the
  interactive transparent variants along with `A`, while
  `core_flow5_without_interactive` drops only `Details`, `Embed`, `Iframe`
  and `Img_interactive`: the two families exclude different tags, so no
  single interactive predicate serves both.
- `metadata_without_title` has no base set here at all: TyXML's `metadata`
  type is unreachable from any element content model at this pin, so slice
  H2 did not project it and no `metadata_without_title ⊆ metadata` statement
  can be made.

Nothing in this module is a claim about the HTML Standard. Every statement is
about the `Whatwg.Html.Schema` transcription of TyXML 4.6.0 (`ocsigen/tyxml`
at `d2916535`); the places where it departs from the standard are the business of
`Whatwg.Html.Content.Divergence`.
-/

namespace Whatwg.Html.Schema

/-! ## Finite enumeration

The two enumerations and the reflection principle over them. -/

/-- Every tag is a member of `Tag.all`. -/
theorem Tag.mem_all (t : Tag) : t ∈ Tag.all := by
  cases t <;> decide

/-- Every content set is a member of `ContentSet.all`. -/
theorem ContentSet.mem_all (c : ContentSet) : c ∈ ContentSet.all := by
  cases c <;> decide

/-- `Tag.all` enumerates the 115 tags of the projection. -/
theorem Tag.all_length : Tag.all.length = 115 := by decide

/-- `ContentSet.all` enumerates the 69 named content sets of the projection. -/
theorem ContentSet.all_length : ContentSet.all.length = 69 := by decide

/-- `Tag.all` lists no tag twice, so with `Tag.mem_all` and `Tag.all_length`
it is an enumeration of the tag universe without repetition. -/
theorem Tag.all_nodup : Tag.all.Nodup := by decide

/-- `ContentSet.all` lists no content set twice. -/
theorem ContentSet.all_nodup : ContentSet.all.Nodup := by decide

/-- Reflection over tags: a boolean predicate that `List.all` accepts on
`Tag.all` holds at every tag. -/
theorem forall_tag_of_all (p : Tag → Bool) (h : Tag.all.all p = true) :
    ∀ t : Tag, p t = true :=
  fun t => List.all_eq_true.mp h t (Tag.mem_all t)

/-- The same reflection at `Prop`, for a decidable predicate on tags. -/
theorem forall_tag_of_decide (p : Tag → Prop) [DecidablePred p]
    (h : Tag.all.all (fun t => decide (p t)) = true) : ∀ t : Tag, p t :=
  fun t => of_decide_eq_true (forall_tag_of_all (fun t => decide (p t)) h t)

/-- Reflection over content sets. -/
theorem forall_contentSet_of_all (p : ContentSet → Bool)
    (h : ContentSet.all.all p = true) : ∀ c : ContentSet, p c = true :=
  fun c => List.all_eq_true.mp h c (ContentSet.mem_all c)

/-- Reflection over the product of the two enumerations, as the transparent
lemmas of `Whatwg.Html.Content.Transparent` need it. -/
theorem forall_contentSet_tag_of_all (p : ContentSet → Tag → Bool)
    (h : ContentSet.all.all (fun c => Tag.all.all (p c)) = true) :
    ∀ (c : ContentSet) (t : Tag), p c t = true :=
  fun c t => forall_tag_of_all (p c) (forall_contentSet_of_all _ h c) t

/-- Reflection over the element rows. -/
theorem forall_elements_of_all (p : Element → Bool) (h : elements.all p = true) :
    ∀ e ∈ elements, p e = true :=
  fun e he => List.all_eq_true.mp h e he

end Whatwg.Html.Schema

namespace Whatwg.Html.Content

open Whatwg.Html.Schema

/-! ## Inclusion

`SubsetOf a b` is pointwise implication of two membership functions, and
`subsetOf_of_all` decides it by one `List.all` over the 115 tags. -/

/-- Pointwise inclusion of two tag-membership functions: every tag `a`
accepts, `b` accepts. -/
def SubsetOf (a b : Tag → Bool) : Prop := ∀ t : Tag, a t = true → b t = true

/-- Pointwise disjointness of two tag-membership functions. -/
def DisjointFrom (a b : Tag → Bool) : Prop := ∀ t : Tag, a t = true → b t = false

/-- Inclusion by reflection over `Tag.all`. -/
theorem subsetOf_of_all {a b : Tag → Bool}
    (h : Tag.all.all (fun t => !a t || b t) = true) : SubsetOf a b := by
  intro t ht
  have hb := forall_tag_of_all (fun t => !a t || b t) h t
  rw [ht] at hb
  simpa using hb

/-- Disjointness by reflection over `Tag.all`. -/
theorem disjointFrom_of_all {a b : Tag → Bool}
    (h : Tag.all.all (fun t => !a t || !b t) = true) : DisjointFrom a b := by
  intro t ht
  have hb := forall_tag_of_all (fun t => !a t || !b t) h t
  rw [ht] at hb
  simpa using hb

/-- Equality of two membership functions by reflection over `Tag.all`. -/
theorem eq_of_all {a b : Tag → Bool}
    (h : Tag.all.all (fun t => a t == b t) = true) : ∀ t : Tag, a t = b t :=
  fun t => eq_of_beq (forall_tag_of_all (fun t => a t == b t) h t)

/-! ### Each `x_without_y` set inside its base

Twenty-seven statements, one per `_without_` set that has a base set in the
projection. `metadata_without_title` is the twenty-eighth `_without_` name
and has no base: see the module docstring. -/

/-- `core_flow5_without_interactive ⊆ core_flow5`. -/
theorem core_flow5_without_interactive_subset_core_flow5 :
    SubsetOf Sets.core_flow5_without_interactive Sets.core_flow5 :=
  subsetOf_of_all (by decide +kernel)

/-- `core_flow5_without_media ⊆ core_flow5`. The inclusion is an equality:
see `core_flow5_without_media_eq_core_flow5`. -/
theorem core_flow5_without_media_subset_core_flow5 :
    SubsetOf Sets.core_flow5_without_media Sets.core_flow5 :=
  subsetOf_of_all (by decide +kernel)

/-- `core_flow5_without_noscript ⊆ core_flow5`. The inclusion is an equality:
see `core_flow5_without_noscript_eq_core_flow5`. -/
theorem core_flow5_without_noscript_subset_core_flow5 :
    SubsetOf Sets.core_flow5_without_noscript Sets.core_flow5 :=
  subsetOf_of_all (by decide +kernel)

/-- `core_phrasing_without_interactive ⊆ core_phrasing`. -/
theorem core_phrasing_without_interactive_subset_core_phrasing :
    SubsetOf Sets.core_phrasing_without_interactive Sets.core_phrasing :=
  subsetOf_of_all (by decide +kernel)

/-- `core_phrasing_without_media ⊆ core_phrasing`. The inclusion is an
equality: see `core_phrasing_without_media_eq_core_phrasing`. -/
theorem core_phrasing_without_media_subset_core_phrasing :
    SubsetOf Sets.core_phrasing_without_media Sets.core_phrasing :=
  subsetOf_of_all (by decide +kernel)

/-- `core_phrasing_without_noscript ⊆ core_phrasing`. The inclusion is an
equality: see `core_phrasing_without_noscript_eq_core_phrasing`. -/
theorem core_phrasing_without_noscript_subset_core_phrasing :
    SubsetOf Sets.core_phrasing_without_noscript Sets.core_phrasing :=
  subsetOf_of_all (by decide +kernel)

/-- `flow5_without_form ⊆ flow5`. -/
theorem flow5_without_form_subset_flow5 :
    SubsetOf Sets.flow5_without_form Sets.flow5 :=
  subsetOf_of_all (by decide +kernel)

/-- `flow5_without_header_footer ⊆ flow5`. -/
theorem flow5_without_header_footer_subset_flow5 :
    SubsetOf Sets.flow5_without_header_footer Sets.flow5 :=
  subsetOf_of_all (by decide +kernel)

/-- `flow5_without_interactive ⊆ flow5`. -/
theorem flow5_without_interactive_subset_flow5 :
    SubsetOf Sets.flow5_without_interactive Sets.flow5 :=
  subsetOf_of_all (by decide +kernel)

/-- `flow5_without_interactive_header_footer ⊆ flow5`. -/
theorem flow5_without_interactive_header_footer_subset_flow5 :
    SubsetOf Sets.flow5_without_interactive_header_footer Sets.flow5 :=
  subsetOf_of_all (by decide +kernel)

/-- `flow5_without_media ⊆ flow5`. -/
theorem flow5_without_media_subset_flow5 :
    SubsetOf Sets.flow5_without_media Sets.flow5 :=
  subsetOf_of_all (by decide +kernel)

/-- `flow5_without_noscript ⊆ flow5`. -/
theorem flow5_without_noscript_subset_flow5 :
    SubsetOf Sets.flow5_without_noscript Sets.flow5 :=
  subsetOf_of_all (by decide +kernel)

/-- `flow5_without_sectioning_heading_header_footer ⊆ flow5`. -/
theorem flow5_without_sectioning_heading_header_footer_subset_flow5 :
    SubsetOf Sets.flow5_without_sectioning_heading_header_footer Sets.flow5 :=
  subsetOf_of_all (by decide +kernel)

/-- `flow5_without_sectioning_heading_header_footer_address ⊆ flow5`. -/
theorem flow5_without_sectioning_heading_header_footer_address_subset_flow5 :
    SubsetOf Sets.flow5_without_sectioning_heading_header_footer_address Sets.flow5 :=
  subsetOf_of_all (by decide +kernel)

/-- `flow5_without_table ⊆ flow5`. -/
theorem flow5_without_table_subset_flow5 :
    SubsetOf Sets.flow5_without_table Sets.flow5 :=
  subsetOf_of_all (by decide +kernel)

/-- `labelable_without_interactive ⊆ labelable`. -/
theorem labelable_without_interactive_subset_labelable :
    SubsetOf Sets.labelable_without_interactive Sets.labelable :=
  subsetOf_of_all (by decide +kernel)

/-- `phrasing_without_dfn ⊆ phrasing`. -/
theorem phrasing_without_dfn_subset_phrasing :
    SubsetOf Sets.phrasing_without_dfn Sets.phrasing :=
  subsetOf_of_all (by decide +kernel)

/-- `phrasing_without_interactive ⊆ phrasing`. -/
theorem phrasing_without_interactive_subset_phrasing :
    SubsetOf Sets.phrasing_without_interactive Sets.phrasing :=
  subsetOf_of_all (by decide +kernel)

/-- `phrasing_without_label ⊆ phrasing`. -/
theorem phrasing_without_label_subset_phrasing :
    SubsetOf Sets.phrasing_without_label Sets.phrasing :=
  subsetOf_of_all (by decide +kernel)

/-- `phrasing_without_media ⊆ phrasing`. -/
theorem phrasing_without_media_subset_phrasing :
    SubsetOf Sets.phrasing_without_media Sets.phrasing :=
  subsetOf_of_all (by decide +kernel)

/-- `phrasing_without_meter ⊆ phrasing`. -/
theorem phrasing_without_meter_subset_phrasing :
    SubsetOf Sets.phrasing_without_meter Sets.phrasing :=
  subsetOf_of_all (by decide +kernel)

/-- `phrasing_without_noscript ⊆ phrasing`. The inclusion is proper by 44
tags: see `phrasing_without_noscript_eq_transparent_without_noscript`. -/
theorem phrasing_without_noscript_subset_phrasing :
    SubsetOf Sets.phrasing_without_noscript Sets.phrasing :=
  subsetOf_of_all (by decide +kernel)

/-- `phrasing_without_progress ⊆ phrasing`. -/
theorem phrasing_without_progress_subset_phrasing :
    SubsetOf Sets.phrasing_without_progress Sets.phrasing :=
  subsetOf_of_all (by decide +kernel)

/-- `phrasing_without_time ⊆ phrasing`. -/
theorem phrasing_without_time_subset_phrasing :
    SubsetOf Sets.phrasing_without_time Sets.phrasing :=
  subsetOf_of_all (by decide +kernel)

/-- `transparent_without_interactive ⊆ transparent`. -/
theorem transparent_without_interactive_subset_transparent :
    SubsetOf Sets.transparent_without_interactive Sets.transparent :=
  subsetOf_of_all (by decide +kernel)

/-- `transparent_without_media ⊆ transparent`. -/
theorem transparent_without_media_subset_transparent :
    SubsetOf Sets.transparent_without_media Sets.transparent :=
  subsetOf_of_all (by decide +kernel)

/-- `transparent_without_noscript ⊆ transparent`. -/
theorem transparent_without_noscript_subset_transparent :
    SubsetOf Sets.transparent_without_noscript Sets.transparent :=
  subsetOf_of_all (by decide +kernel)

/-! ### Each `core_x` set inside `x`

Seven of the eight `core_` sets are inside the set they are named after. The
eighth, `core_phrasing_without_noscript`, is not: it is disjoint from
`phrasing_without_noscript`, which is recorded below rather than repaired. -/

/-- `core_flow5 ⊆ flow5`. -/
theorem core_flow5_subset_flow5 : SubsetOf Sets.core_flow5 Sets.flow5 :=
  subsetOf_of_all (by decide +kernel)

/-- `core_flow5_without_interactive ⊆ flow5_without_interactive`. -/
theorem core_flow5_without_interactive_subset_flow5_without_interactive :
    SubsetOf Sets.core_flow5_without_interactive Sets.flow5_without_interactive :=
  subsetOf_of_all (by decide +kernel)

/-- `core_flow5_without_media ⊆ flow5_without_media`. -/
theorem core_flow5_without_media_subset_flow5_without_media :
    SubsetOf Sets.core_flow5_without_media Sets.flow5_without_media :=
  subsetOf_of_all (by decide +kernel)

/-- `core_flow5_without_noscript ⊆ flow5_without_noscript`. -/
theorem core_flow5_without_noscript_subset_flow5_without_noscript :
    SubsetOf Sets.core_flow5_without_noscript Sets.flow5_without_noscript :=
  subsetOf_of_all (by decide +kernel)

/-- `core_phrasing ⊆ phrasing`. -/
theorem core_phrasing_subset_phrasing : SubsetOf Sets.core_phrasing Sets.phrasing :=
  subsetOf_of_all (by decide +kernel)

/-- `core_phrasing_without_interactive ⊆ phrasing_without_interactive`. -/
theorem core_phrasing_without_interactive_subset_phrasing_without_interactive :
    SubsetOf Sets.core_phrasing_without_interactive Sets.phrasing_without_interactive :=
  subsetOf_of_all (by decide +kernel)

/-- `core_phrasing_without_media ⊆ phrasing_without_media`. -/
theorem core_phrasing_without_media_subset_phrasing_without_media :
    SubsetOf Sets.core_phrasing_without_media Sets.phrasing_without_media :=
  subsetOf_of_all (by decide +kernel)

/-- The eighth `core_` pair fails, and fails maximally: at this pin
`core_phrasing_without_noscript` (43 tags) and `phrasing_without_noscript`
(11 tags) have no tag in common, because TyXML defines the second as the
transparent row alone. The tag `Abbr` witnesses the failed inclusion. -/
theorem core_phrasing_without_noscript_disjoint_phrasing_without_noscript :
    DisjointFrom Sets.core_phrasing_without_noscript Sets.phrasing_without_noscript :=
  disjointFrom_of_all (by decide +kernel)

/-- `core_phrasing_without_noscript` is nonetheless inside `phrasing`. -/
theorem core_phrasing_without_noscript_subset_phrasing :
    SubsetOf Sets.core_phrasing_without_noscript Sets.phrasing :=
  subsetOf_of_all (by decide +kernel)

/-! ### The category sets inside `flow5` and `phrasing` -/

/-- `phrasing ⊆ flow5`. -/
theorem phrasing_subset_flow5 : SubsetOf Sets.phrasing Sets.flow5 :=
  subsetOf_of_all (by decide +kernel)

/-- `heading ⊆ flow5`. -/
theorem heading_subset_flow5 : SubsetOf Sets.heading Sets.flow5 :=
  subsetOf_of_all (by decide +kernel)

/-- `sectioning ⊆ flow5`. -/
theorem sectioning_subset_flow5 : SubsetOf Sets.sectioning Sets.flow5 :=
  subsetOf_of_all (by decide +kernel)

/-- `formatblock ⊆ flow5`. -/
theorem formatblock_subset_flow5 : SubsetOf Sets.formatblock Sets.flow5 :=
  subsetOf_of_all (by decide +kernel)

/-- `formassociated ⊆ flow5`. -/
theorem formassociated_subset_flow5 : SubsetOf Sets.formassociated Sets.flow5 :=
  subsetOf_of_all (by decide +kernel)

/-- `labelable ⊆ flow5`. -/
theorem labelable_subset_flow5 : SubsetOf Sets.labelable Sets.flow5 :=
  subsetOf_of_all (by decide +kernel)

/-- `listed ⊆ flow5`. -/
theorem listed_subset_flow5 : SubsetOf Sets.listed Sets.flow5 :=
  subsetOf_of_all (by decide +kernel)

/-- `resetable ⊆ flow5`. -/
theorem resetable_subset_flow5 : SubsetOf Sets.resetable Sets.flow5 :=
  subsetOf_of_all (by decide +kernel)

/-- `submitable ⊆ flow5`. -/
theorem submitable_subset_flow5 : SubsetOf Sets.submitable Sets.flow5 :=
  subsetOf_of_all (by decide +kernel)

/-- `transparent ⊆ flow5`. -/
theorem transparent_subset_flow5 : SubsetOf Sets.transparent Sets.flow5 :=
  subsetOf_of_all (by decide +kernel)

/-- `heading ⊆ formatblock`. -/
theorem heading_subset_formatblock : SubsetOf Sets.heading Sets.formatblock :=
  subsetOf_of_all (by decide +kernel)

/-- `sectioning ⊆ formatblock`. -/
theorem sectioning_subset_formatblock : SubsetOf Sets.sectioning Sets.formatblock :=
  subsetOf_of_all (by decide +kernel)

/-- `labelable ⊆ phrasing`. -/
theorem labelable_subset_phrasing : SubsetOf Sets.labelable Sets.phrasing :=
  subsetOf_of_all (by decide +kernel)

/-- `resetable ⊆ phrasing`. -/
theorem resetable_subset_phrasing : SubsetOf Sets.resetable Sets.phrasing :=
  subsetOf_of_all (by decide +kernel)

/-- `submitable ⊆ phrasing`. -/
theorem submitable_subset_phrasing : SubsetOf Sets.submitable Sets.phrasing :=
  subsetOf_of_all (by decide +kernel)

/-- `transparent ⊆ phrasing`: every tag TyXML admits transparently is also a
phrasing tag at this pin. -/
theorem transparent_subset_phrasing : SubsetOf Sets.transparent Sets.phrasing :=
  subsetOf_of_all (by decide +kernel)

/-- `notag` is inside every content set, vacuously. -/
theorem notag_subset (b : Tag → Bool) : SubsetOf Sets.notag b :=
  fun _ h => absurd h (by simp [Sets.notag])

/-! ## Separation -/

/-- `notag` admits no tag. -/
theorem notag_false (t : Tag) : Sets.notag t = false := rfl

/-- `ContentSet.notag` admits no tag. -/
theorem contains_notag_false (t : Tag) : ContentSet.contains .notag t = false := rfl

/-- Every void element row carries the empty content set. Stated over the 111
element rows, so both the `table` and the `tablex` row are covered. -/
theorem void_content_notag :
    ∀ e ∈ elements, (Element.tag e).isVoid = true → Element.content e = some .notag := by
  intro e he hv
  have h := forall_elements_of_all
    (fun e => !(Element.tag e).isVoid || (Element.content e == some ContentSet.notag))
    (by decide +kernel) e he
  rw [hv] at h
  simpa using h

/-- The same fact through `Tag.element?`, which is the form the typed tree
uses: a void tag resolves to the empty content set. -/
theorem void_element_content_notag :
    ∀ t : Tag, t.isVoid = true → (Tag.element? t).bind Element.content = some .notag := by
  intro t hv
  have h := forall_tag_of_all
    (fun t => !t.isVoid || ((Tag.element? t).bind Element.content == some ContentSet.notag))
    (by decide +kernel) t
  rw [hv] at h
  simpa using h

/-- Every void tag has an element constructor. -/
theorem void_element_isSome : ∀ t : Tag, t.isVoid = true → (Tag.element? t).isSome = true := by
  intro t hv
  have h := forall_tag_of_all (fun t => !t.isVoid || (Tag.element? t).isSome) (by decide +kernel) t
  rw [hv] at h
  simpa using h

/-- The converse of `void_content_notag` fails. Two element rows are not void
and still carry `notag`: `datalist` (whose TyXML constructor takes either
phrasing children or `option` children, and whose plain content set is
therefore empty) and `menu`. This theorem records that such a row exists;
`Whatwg.Html.Content.Divergence` owns the reading of it. -/
theorem exists_nonvoid_notag_content :
    elements.any (fun e =>
      !(Element.tag e).isVoid && (Element.content e == some ContentSet.notag)) = true := by
  decide

/-! ## Boolean decompositions

One exclusion predicate per distinct difference, then one decomposition
theorem per `_without_` family. The predicates are the computed differences,
not TyXML type names: `Excluded.flow5Interactive` is exactly
`flow5 \ flow5_without_interactive` and nothing else. -/

namespace Excluded

/-- The empty exclusion, for the four `_without_` sets that exclude nothing. -/
def nothing : Tag → Bool := fun _ => false

/-- `core_flow5 \ core_flow5_without_interactive`. -/
def coreFlow5Interactive : Tag → Bool
  | .details | .embed | .iframe | .img_interactive => true
  | _ => false

/-- `core_phrasing \ core_phrasing_without_interactive`. -/
def corePhrasingInteractive : Tag → Bool
  | .button | .embed | .iframe | .img_interactive | .input | .keygen
  | .label | .output | .select | .textarea => true
  | _ => false

/-- `flow5 \ flow5_without_interactive`. Wider than
`coreFlow5Interactive` by the four transparent interactive variants `A`,
`Audio_interactive`, `Object_interactive`, `Video_interactive`, and narrower
than `corePhrasingInteractive`, which excludes the form controls. -/
def flow5Interactive : Tag → Bool
  | .a | .audio_interactive | .details | .embed | .iframe | .img_interactive
  | .object_interactive | .video_interactive => true
  | _ => false

/-- `flow5 \ flow5_without_interactive_header_footer`: `flow5Interactive`
together with `Footer` and `Header`. -/
def flow5InteractiveHeaderFooter : Tag → Bool
  | .a | .audio_interactive | .details | .embed | .footer | .header | .iframe
  | .img_interactive | .object_interactive | .video_interactive => true
  | _ => false

/-- `phrasing \ phrasing_without_interactive`: `flow5Interactive` without
`Details` and with the six form controls and `Label`. -/
def phrasingInteractive : Tag → Bool
  | .a | .audio_interactive | .button | .embed | .iframe | .img_interactive
  | .input | .keygen | .label | .object_interactive | .output | .select
  | .textarea | .video_interactive => true
  | _ => false

/-- `labelable \ labelable_without_interactive`. -/
def labelableInteractive : Tag → Bool
  | .button | .input | .keygen | .output | .select | .textarea => true
  | _ => false

/-- The media exclusion, shared by `flow5_without_media`,
`phrasing_without_media` and `transparent_without_media`. -/
def media : Tag → Bool
  | .audio | .audio_interactive | .video | .video_interactive => true
  | _ => false

/-- The noscript exclusion, shared by `flow5_without_noscript` and
`transparent_without_noscript`. It is *not* the exclusion of
`phrasing_without_noscript`: see `phrasingNoscript`. -/
def noscript : Tag → Bool
  | .noscript => true
  | _ => false

/-- `flow5 \ flow5_without_form`. -/
def form : Tag → Bool
  | .form => true
  | _ => false

/-- `flow5 \ flow5_without_header_footer`. -/
def headerFooter : Tag → Bool
  | .footer | .header => true
  | _ => false

/-- `flow5 \ flow5_without_table`. -/
def table : Tag → Bool
  | .table => true
  | _ => false

/-- `flow5 \ flow5_without_sectioning_heading_header_footer`. -/
def sectioningHeadingHeaderFooter : Tag → Bool
  | .article | .aside | .footer | .h1 | .h2 | .h3 | .h4 | .h5 | .h6
  | .header | .hgroup | .nav | .«section» => true
  | _ => false

/-- `flow5 \ flow5_without_sectioning_heading_header_footer_address`. -/
def sectioningHeadingHeaderFooterAddress : Tag → Bool
  | .address | .article | .aside | .footer | .h1 | .h2 | .h3 | .h4 | .h5 | .h6
  | .header | .hgroup | .nav | .«section» => true
  | _ => false

/-- `phrasing \ phrasing_without_dfn`. `Embed`, `Iframe` and `Svg` are
excluded along with `Dfn`: TyXML's `phrasing_without_dfn` is an explicit
inclusion list that omits them. -/
def phrasingDfn : Tag → Bool
  | .dfn | .embed | .iframe | .svg => true
  | _ => false

/-- `phrasing \ phrasing_without_label`, with the same three extra tags. -/
def phrasingLabel : Tag → Bool
  | .embed | .iframe | .label | .svg => true
  | _ => false

/-- `phrasing \ phrasing_without_meter`, with the same three extra tags. -/
def phrasingMeter : Tag → Bool
  | .embed | .iframe | .meter | .svg => true
  | _ => false

/-- `phrasing \ phrasing_without_progress`, with the same three extra tags. -/
def phrasingProgress : Tag → Bool
  | .embed | .iframe | .progress | .svg => true
  | _ => false

/-- `phrasing \ phrasing_without_time`, with the same three extra tags. -/
def phrasingTime : Tag → Bool
  | .embed | .iframe | .svg | .time => true
  | _ => false

/-- `phrasing \ phrasing_without_noscript`: 44 of the 55 phrasing tags.
TyXML defines `phrasing_without_noscript` as the transparent row alone, so
everything outside that row is excluded, not just `Noscript`. -/
def phrasingNoscript : Tag → Bool
  | .abbr | .b | .bdo | .br | .button | .cite | .code | .command
  | .datalist | .dfn | .em | .embed | .i | .iframe | .img | .img_interactive
  | .input | .kbd | .keygen | .label | .mark | .meter | .noscript | .output
  | .pcdata | .picture | .progress | .q | .ruby | .samp | .script | .select
  | .small | .span | .strong | .sub | .sup | .svg | .template | .textarea
  | .time | .u | .var | .wbr => true
  | _ => false

/-- `transparent \ transparent_without_interactive`. -/
def transparentInteractive : Tag → Bool
  | .a | .audio_interactive | .object_interactive | .video_interactive => true
  | _ => false

end Excluded

/-- `core_flow5_without_interactive` is `core_flow5` minus `Details`,
`Embed`, `Iframe` and `Img_interactive`. -/
theorem core_flow5_without_interactive_decomposition : ∀ t : Tag,
    Sets.core_flow5_without_interactive t
      = (Sets.core_flow5 t && !Excluded.coreFlow5Interactive t) :=
  eq_of_all (by decide +kernel)

/-- `core_flow5_without_media` excludes nothing from `core_flow5`: no media
tag is in `core_flow5` to begin with. -/
theorem core_flow5_without_media_decomposition : ∀ t : Tag,
    Sets.core_flow5_without_media t = (Sets.core_flow5 t && !Excluded.nothing t) :=
  eq_of_all (by decide +kernel)

/-- The same fact as a plain equality of membership functions. -/
theorem core_flow5_without_media_eq_core_flow5 : ∀ t : Tag,
    Sets.core_flow5_without_media t = Sets.core_flow5 t :=
  eq_of_all (by decide +kernel)

/-- `core_flow5_without_noscript` excludes nothing from `core_flow5`. -/
theorem core_flow5_without_noscript_decomposition : ∀ t : Tag,
    Sets.core_flow5_without_noscript t = (Sets.core_flow5 t && !Excluded.nothing t) :=
  eq_of_all (by decide +kernel)

/-- The same fact as a plain equality of membership functions. -/
theorem core_flow5_without_noscript_eq_core_flow5 : ∀ t : Tag,
    Sets.core_flow5_without_noscript t = Sets.core_flow5 t :=
  eq_of_all (by decide +kernel)

/-- `core_phrasing_without_interactive` is `core_phrasing` minus the ten tags
of `Excluded.corePhrasingInteractive`. -/
theorem core_phrasing_without_interactive_decomposition : ∀ t : Tag,
    Sets.core_phrasing_without_interactive t
      = (Sets.core_phrasing t && !Excluded.corePhrasingInteractive t) :=
  eq_of_all (by decide +kernel)

/-- `core_phrasing_without_media` excludes nothing from `core_phrasing`. -/
theorem core_phrasing_without_media_decomposition : ∀ t : Tag,
    Sets.core_phrasing_without_media t = (Sets.core_phrasing t && !Excluded.nothing t) :=
  eq_of_all (by decide +kernel)

/-- The same fact as a plain equality of membership functions. -/
theorem core_phrasing_without_media_eq_core_phrasing : ∀ t : Tag,
    Sets.core_phrasing_without_media t = Sets.core_phrasing t :=
  eq_of_all (by decide +kernel)

/-- `core_phrasing_without_noscript` excludes nothing from `core_phrasing`,
including `Noscript`, which was never a member. -/
theorem core_phrasing_without_noscript_decomposition : ∀ t : Tag,
    Sets.core_phrasing_without_noscript t = (Sets.core_phrasing t && !Excluded.nothing t) :=
  eq_of_all (by decide +kernel)

/-- The same fact as a plain equality of membership functions. -/
theorem core_phrasing_without_noscript_eq_core_phrasing : ∀ t : Tag,
    Sets.core_phrasing_without_noscript t = Sets.core_phrasing t :=
  eq_of_all (by decide +kernel)

/-- `flow5_without_form` is `flow5` minus `Form`. -/
theorem flow5_without_form_decomposition : ∀ t : Tag,
    Sets.flow5_without_form t = (Sets.flow5 t && !Excluded.form t) :=
  eq_of_all (by decide +kernel)

/-- `flow5_without_header_footer` is `flow5` minus `Footer` and `Header`. -/
theorem flow5_without_header_footer_decomposition : ∀ t : Tag,
    Sets.flow5_without_header_footer t = (Sets.flow5 t && !Excluded.headerFooter t) :=
  eq_of_all (by decide +kernel)

/-- `flow5_without_interactive` is `flow5` minus the eight tags of
`Excluded.flow5Interactive`. -/
theorem flow5_without_interactive_decomposition : ∀ t : Tag,
    Sets.flow5_without_interactive t = (Sets.flow5 t && !Excluded.flow5Interactive t) :=
  eq_of_all (by decide +kernel)

/-- `flow5_without_interactive_header_footer` is `flow5` minus those eight
tags together with `Footer` and `Header`. -/
theorem flow5_without_interactive_header_footer_decomposition : ∀ t : Tag,
    Sets.flow5_without_interactive_header_footer t
      = (Sets.flow5 t && !Excluded.flow5InteractiveHeaderFooter t) :=
  eq_of_all (by decide +kernel)

/-- `flow5_without_media` is `flow5` minus the four media tags. -/
theorem flow5_without_media_decomposition : ∀ t : Tag,
    Sets.flow5_without_media t = (Sets.flow5 t && !Excluded.media t) :=
  eq_of_all (by decide +kernel)

/-- `flow5_without_noscript` is `flow5` minus `Noscript`. -/
theorem flow5_without_noscript_decomposition : ∀ t : Tag,
    Sets.flow5_without_noscript t = (Sets.flow5 t && !Excluded.noscript t) :=
  eq_of_all (by decide +kernel)

/-- `flow5_without_sectioning_heading_header_footer` is `flow5` minus the
thirteen sectioning, heading, header and footer tags. -/
theorem flow5_without_sectioning_heading_header_footer_decomposition : ∀ t : Tag,
    Sets.flow5_without_sectioning_heading_header_footer t
      = (Sets.flow5 t && !Excluded.sectioningHeadingHeaderFooter t) :=
  eq_of_all (by decide +kernel)

/-- `flow5_without_sectioning_heading_header_footer_address` is `flow5` minus
those thirteen tags and `Address`. -/
theorem flow5_without_sectioning_heading_header_footer_address_decomposition : ∀ t : Tag,
    Sets.flow5_without_sectioning_heading_header_footer_address t
      = (Sets.flow5 t && !Excluded.sectioningHeadingHeaderFooterAddress t) :=
  eq_of_all (by decide +kernel)

/-- `flow5_without_table` is `flow5` minus `Table`. -/
theorem flow5_without_table_decomposition : ∀ t : Tag,
    Sets.flow5_without_table t = (Sets.flow5 t && !Excluded.table t) :=
  eq_of_all (by decide +kernel)

/-- `labelable_without_interactive` is `labelable` minus the six form
controls, leaving `Meter` and `Progress`. -/
theorem labelable_without_interactive_decomposition : ∀ t : Tag,
    Sets.labelable_without_interactive t
      = (Sets.labelable t && !Excluded.labelableInteractive t) :=
  eq_of_all (by decide +kernel)

/-- `phrasing_without_dfn` is `phrasing` minus `Dfn`, `Embed`, `Iframe` and
`Svg`. -/
theorem phrasing_without_dfn_decomposition : ∀ t : Tag,
    Sets.phrasing_without_dfn t = (Sets.phrasing t && !Excluded.phrasingDfn t) :=
  eq_of_all (by decide +kernel)

/-- `phrasing_without_interactive` is `phrasing` minus the fourteen tags of
`Excluded.phrasingInteractive`. -/
theorem phrasing_without_interactive_decomposition : ∀ t : Tag,
    Sets.phrasing_without_interactive t
      = (Sets.phrasing t && !Excluded.phrasingInteractive t) :=
  eq_of_all (by decide +kernel)

/-- `phrasing_without_label` is `phrasing` minus `Label`, `Embed`, `Iframe`
and `Svg`. -/
theorem phrasing_without_label_decomposition : ∀ t : Tag,
    Sets.phrasing_without_label t = (Sets.phrasing t && !Excluded.phrasingLabel t) :=
  eq_of_all (by decide +kernel)

/-- `phrasing_without_media` is `phrasing` minus the four media tags. -/
theorem phrasing_without_media_decomposition : ∀ t : Tag,
    Sets.phrasing_without_media t = (Sets.phrasing t && !Excluded.media t) :=
  eq_of_all (by decide +kernel)

/-- `phrasing_without_meter` is `phrasing` minus `Meter`, `Embed`, `Iframe`
and `Svg`. -/
theorem phrasing_without_meter_decomposition : ∀ t : Tag,
    Sets.phrasing_without_meter t = (Sets.phrasing t && !Excluded.phrasingMeter t) :=
  eq_of_all (by decide +kernel)

/-- `phrasing_without_noscript` is `phrasing` minus 44 of its 55 tags. The
name says `Noscript`; the data says everything except the eleven transparent
tags `A`, `Audio`, `Audio_interactive`, `Canvas`, `Del`, `Ins`, `Map`,
`Object`, `Object_interactive`, `Video`, `Video_interactive`. -/
theorem phrasing_without_noscript_decomposition : ∀ t : Tag,
    Sets.phrasing_without_noscript t = (Sets.phrasing t && !Excluded.phrasingNoscript t) :=
  eq_of_all (by decide +kernel)

/-- The consequence of that definition: `phrasing_without_noscript` and
`transparent_without_noscript` are the same membership function. -/
theorem phrasing_without_noscript_eq_transparent_without_noscript : ∀ t : Tag,
    Sets.phrasing_without_noscript t = Sets.transparent_without_noscript t :=
  eq_of_all (by decide +kernel)

/-- `phrasing_without_progress` is `phrasing` minus `Progress`, `Embed`,
`Iframe` and `Svg`. -/
theorem phrasing_without_progress_decomposition : ∀ t : Tag,
    Sets.phrasing_without_progress t = (Sets.phrasing t && !Excluded.phrasingProgress t) :=
  eq_of_all (by decide +kernel)

/-- `phrasing_without_time` is `phrasing` minus `Time`, `Embed`, `Iframe` and
`Svg`. -/
theorem phrasing_without_time_decomposition : ∀ t : Tag,
    Sets.phrasing_without_time t = (Sets.phrasing t && !Excluded.phrasingTime t) :=
  eq_of_all (by decide +kernel)

/-- `transparent_without_interactive` is `transparent` minus `A` and the
three interactive transparent variants. -/
theorem transparent_without_interactive_decomposition : ∀ t : Tag,
    Sets.transparent_without_interactive t
      = (Sets.transparent t && !Excluded.transparentInteractive t) :=
  eq_of_all (by decide +kernel)

/-- `transparent_without_media` is `transparent` minus the four media tags. -/
theorem transparent_without_media_decomposition : ∀ t : Tag,
    Sets.transparent_without_media t = (Sets.transparent t && !Excluded.media t) :=
  eq_of_all (by decide +kernel)

/-- `transparent_without_noscript` is `transparent` minus `Noscript`. -/
theorem transparent_without_noscript_decomposition : ∀ t : Tag,
    Sets.transparent_without_noscript t = (Sets.transparent t && !Excluded.noscript t) :=
  eq_of_all (by decide +kernel)

end Whatwg.Html.Content
