import Whatwg.Streams

/-! Frozen P6a theorem receipt list; all 118 staged and composed obligations. -/

#print axioms Whatwg.Streams.Transform.withReadable_eq
#print axioms Whatwg.Streams.Transform.withWritable_eq
#print axioms Whatwg.Streams.Transform.lookupPromise_eq
#print axioms Whatwg.Streams.Transform.freshInternal_eq
#print axioms Whatwg.Streams.Transform.freshInternal_old
#print axioms Whatwg.Streams.Transform.freshInternal_new
#print axioms Whatwg.Streams.Transform.freshInternal_identity
#print axioms Whatwg.Streams.Transform.subscriptionPromise_readable
#print axioms Whatwg.Streams.Transform.subscriptionPromise_writable
#print axioms Whatwg.Streams.Transform.subscriptionPromise_reaction
#print axioms Whatwg.Streams.Transform.notify_readable
#print axioms Whatwg.Streams.Transform.notify_writable
#print axioms Whatwg.Streams.Transform.notify_reaction
#print axioms Whatwg.Streams.Transform.subscribe_pending
#print axioms Whatwg.Streams.Transform.subscribe_fulfilled
#print axioms Whatwg.Streams.Transform.subscribe_rejected
#print axioms Whatwg.Streams.Transform.subscribe_missing
#print axioms Whatwg.Streams.Transform.settle_other
#print axioms Whatwg.Streams.Transform.settle_pending
#print axioms Whatwg.Streams.Transform.setBackpressure_same
#print axioms Whatwg.Streams.Transform.setBackpressure_change
#print axioms Whatwg.Streams.Transform.unblockWrite_true
#print axioms Whatwg.Streams.Transform.unblockWrite_false
#print axioms Whatwg.Streams.Transform.sourcePull_realizes
#print axioms Whatwg.Streams.Transform.sourcePull_requires_pressure
#print axioms Whatwg.Streams.Transform.sourcePull_requires_frame
#print axioms Whatwg.Streams.Transform.servicePull_empty
#print axioms Whatwg.Streams.Transform.servicePull_pull
#print axioms Whatwg.Streams.Transform.servicePull_size
#print axioms Whatwg.Streams.Transform.read_eq
#print axioms Whatwg.Streams.Transform.performTransform_present
#print axioms Whatwg.Streams.Transform.performTransform_missing
#print axioms Whatwg.Streams.Transform.react_write_writable
#print axioms Whatwg.Streams.Transform.react_write_erroring
#print axioms Whatwg.Streams.Transform.react_write_closed
#print axioms Whatwg.Streams.Transform.react_write_errored
#print axioms Whatwg.Streams.Transform.react_write_rejected
#print axioms Whatwg.Streams.Transform.react_transform_fulfilled
#print axioms Whatwg.Streams.Transform.react_transform_rejected
#print axioms Whatwg.Streams.Transform.react_adopt
#print axioms Whatwg.Streams.Transform.error_eq
#print axioms Whatwg.Streams.Transform.terminate_eq
#print axioms Whatwg.Streams.Transform.sinkWrite_blocked
#print axioms Whatwg.Streams.Transform.sinkWrite_direct
#print axioms Whatwg.Streams.Transform.sinkWrite_inside_transform
#print axioms Whatwg.Streams.Transform.sinkWrite_requires_frame
#print axioms Whatwg.Streams.Transform.answerTransform_waiting
#print axioms Whatwg.Streams.Transform.answerTransform_unmatched
#print axioms Whatwg.Streams.Transform.returnTransform_frame
#print axioms Whatwg.Streams.Transform.returnTransform_unmatched
#print axioms Whatwg.Streams.Transform.returnTransform_nested_writable
#print axioms Whatwg.Streams.Transform.returnTransform_readable_frame
#print axioms Whatwg.Streams.Transform.enqueue_guard
#print axioms Whatwg.Streams.Transform.enqueue_same_pressure
#print axioms Whatwg.Streams.Transform.enqueue_raises_pressure
#print axioms Whatwg.Streams.Transform.enqueue_requires_count
#print axioms Whatwg.Streams.Transform.runJob_reaction
#print axioms Whatwg.Streams.Transform.runJob_readable
#print axioms Whatwg.Streams.Transform.runJob_writable
#print axioms Whatwg.Streams.Transform.runJob_writable_requires_matching
#print axioms Whatwg.Streams.Transform.tick_errorWritable
#print axioms Whatwg.Streams.Transform.tick_waitWritable_done
#print axioms Whatwg.Streams.Transform.tick_waitWritable_step
#print axioms Whatwg.Streams.Transform.tick_unblock
#print axioms Whatwg.Streams.Transform.tick_settle
#print axioms Whatwg.Streams.Transform.tick_await_nested_writable
#print axioms Whatwg.Streams.Transform.tick_await_suspended
#print axioms Whatwg.Streams.Transform.tick_writable_control
#print axioms Whatwg.Streams.Transform.tick_native_write
#print axioms Whatwg.Streams.Transform.tick_job_fifo
#print axioms Whatwg.Streams.Transform.tick_no_job
#print axioms Whatwg.Streams.Transform.tick_native_pull
#print axioms Whatwg.Streams.Transform.externalFrontier_native_write
#print axioms Whatwg.Streams.Transform.externalFrontier_administrative
#print axioms Whatwg.Streams.Transform.decide_nonfrontier
#print axioms Whatwg.Streams.Transform.step_iff
#print axioms Whatwg.Streams.Transform.reaches_nil
#print axioms Whatwg.Streams.Transform.reaches_cons
#print axioms Whatwg.Streams.Transform.reaches_append
#print axioms Whatwg.Streams.Transform.tick_waitWritable_undershoot
#print axioms Whatwg.Streams.Transform.initial_eq
#print axioms Whatwg.Streams.Transform.externalFrontier_eq
#print axioms Whatwg.Streams.Transform.decide_read
#print axioms Whatwg.Streams.Transform.decide_enqueue
#print axioms Whatwg.Streams.Transform.decide_error
#print axioms Whatwg.Streams.Transform.decide_terminate
#print axioms Whatwg.Streams.Transform.decide_write
#print axioms Whatwg.Streams.Transform.decide_returnSize
#print axioms Whatwg.Streams.Transform.decide_ready
#print axioms Whatwg.Streams.Transform.decide_closed
#print axioms Whatwg.Streams.Transform.decide_writerDesiredSize
#print axioms Whatwg.Streams.Transform.decide_desiredSize
#print axioms Whatwg.Streams.Transform.decide_returnTransform
#print axioms Whatwg.Streams.Transform.decide_answerTransform
#print axioms Whatwg.Streams.Transform.coupled_write_read_enqueue
#print axioms Whatwg.Streams.Transform.coupled_error_during_transform
#print axioms Whatwg.Streams.Transform.observeOutput_eq
#print axioms Whatwg.Streams.Transform.observeOrdered_eq
#print axioms Whatwg.Streams.Transform.observeOrdered_output
#print axioms Whatwg.Streams.Transform.visible_readable_settlement
#print axioms Whatwg.Streams.Transform.visible_readable_query
#print axioms Whatwg.Streams.Transform.visible_internal_settlement
#print axioms Whatwg.Streams.Transform.visible_external_settlement
#print axioms Whatwg.Streams.Transform.visible_writer_returned
#print axioms Whatwg.Streams.Transform.visible_ready_query
#print axioms Whatwg.Streams.Transform.visible_closed_query
#print axioms Whatwg.Streams.Transform.visible_writer_size_query
#print axioms Whatwg.Streams.Transform.visible_writer_controller_return
#print axioms Whatwg.Streams.Transform.visible_enqueue_return
#print axioms Whatwg.Streams.Transform.visible_nested_readable_enqueue
#print axioms Whatwg.Streams.Transform.visible_transform_call
#print axioms Whatwg.Streams.Transform.visible_transform_return
#print axioms Whatwg.Streams.Transform.visible_readable_pull_call
#print axioms Whatwg.Streams.Transform.visible_readable_size_call
#print axioms Whatwg.Streams.Transform.visible_writable_sink_call
#print axioms Whatwg.Streams.Transform.visible_writable_size_call
#print axioms Whatwg.Streams.Transform.visible_writable_signal_call
#print axioms Whatwg.Streams.Transform.coupled_positive_readable_capacity
