import Whatwg.Streams

/-! P5a theorem trust receipt. Frozen with WRITABLE-PG-DEFAULT, 2026-09-05. -/

#print axioms Whatwg.Streams.Writable.size_eq
#print axioms Whatwg.Streams.Writable.sizes_eq
#print axioms Whatwg.Streams.Writable.unitPromise_eq
#print axioms Whatwg.Streams.Writable.unitPromiseToShared_eq
#print axioms Whatwg.Streams.Writable.unitPromiseFromShared_eq
#print axioms Whatwg.Streams.Writable.unitPromise_roundtrip
#print axioms Whatwg.Streams.Writable.sinkAnswer_eq
#print axioms Whatwg.Streams.Writable.sinkAnswerToShared_eq
#print axioms Whatwg.Streams.Writable.sinkAnswerFromShared_eq
#print axioms Whatwg.Streams.Writable.sinkAnswer_roundtrip
#print axioms Whatwg.Streams.Writable.sinkReturn_eq
#print axioms Whatwg.Streams.Writable.sinkReturnToShared_eq
#print axioms Whatwg.Streams.Writable.sinkReturnFromShared_eq
#print axioms Whatwg.Streams.Writable.sinkReturn_roundtrip
#print axioms Whatwg.Streams.Writable.initial_eq
#print axioms Whatwg.Streams.Writable.lookupPromise_eq
#print axioms Whatwg.Streams.Writable.freshPromise_pending
#print axioms Whatwg.Streams.Writable.freshPromise_fulfilled
#print axioms Whatwg.Streams.Writable.freshPromise_rejected
#print axioms Whatwg.Streams.Writable.settle_pending
#print axioms Whatwg.Streams.Writable.settle_other
#print axioms Whatwg.Streams.Writable.markHandled_eq
#print axioms Whatwg.Streams.Writable.ensureReadyRejected_pending
#print axioms Whatwg.Streams.Writable.ensureReadyRejected_other
#print axioms Whatwg.Streams.Writable.updateBackpressure_same
#print axioms Whatwg.Streams.Writable.updateBackpressure_true
#print axioms Whatwg.Streams.Writable.updateBackpressure_false
#print axioms Whatwg.Streams.Writable.desiredSize_eq
#print axioms Whatwg.Streams.Writable.getBackpressure_eq
#print axioms Whatwg.Streams.Writable.clearAlgorithms_eq
#print axioms Whatwg.Streams.Writable.closeQueuedOrInFlight_eq
#print axioms Whatwg.Streams.Writable.hasInFlight_eq
#print axioms Whatwg.Streams.Writable.externalFrontier_eq
#print axioms Whatwg.Streams.Writable.operationKind_eq
#print axioms Whatwg.Streams.Writable.operationRequest_eq
#print axioms Whatwg.Streams.Writable.operationPhase_eq
#print axioms Whatwg.Streams.Writable.setOperationPhase_eq
#print axioms Whatwg.Streams.Writable.attachSink_eq
#print axioms Whatwg.Streams.Writable.invokeSink_eq
#print axioms Whatwg.Streams.Writable.acceptAnswer_waiting
#print axioms Whatwg.Streams.Writable.acceptAnswer_other
#print axioms Whatwg.Streams.Writable.sizeNonPositive_eq
#print axioms Whatwg.Streams.Writable.decide_blocked
#print axioms Whatwg.Streams.Writable.decide_write
#print axioms Whatwg.Streams.Writable.decide_close
#print axioms Whatwg.Streams.Writable.decide_abort
#print axioms Whatwg.Streams.Writable.decide_controllerError
#print axioms Whatwg.Streams.Writable.decide_queryReady
#print axioms Whatwg.Streams.Writable.decide_queryClosed
#print axioms Whatwg.Streams.Writable.decide_queryDesiredSize
#print axioms Whatwg.Streams.Writable.decide_answer
#print axioms Whatwg.Streams.Writable.returnSize_value
#print axioms Whatwg.Streams.Writable.returnSize_thrown
#print axioms Whatwg.Streams.Writable.returnSize_unmatched
#print axioms Whatwg.Streams.Writable.returnSink_invoking
#print axioms Whatwg.Streams.Writable.returnSink_unmatched
#print axioms Whatwg.Streams.Writable.returnSignal_eq
#print axioms Whatwg.Streams.Writable.returnSignal_unmatched
#print axioms Whatwg.Streams.Writable.tick_foreign_marker
#print axioms Whatwg.Streams.Writable.tick_no_job
#print axioms Whatwg.Streams.Writable.tick_job_fifo
#print axioms Whatwg.Streams.Writable.tick_returnPromise
#print axioms Whatwg.Streams.Writable.tick_returnUnit
#print axioms Whatwg.Streams.Writable.tick_getSize
#print axioms Whatwg.Streams.Writable.tick_afterSize_errored
#print axioms Whatwg.Streams.Writable.tick_afterSize_closing
#print axioms Whatwg.Streams.Writable.tick_afterSize_erroring
#print axioms Whatwg.Streams.Writable.tick_afterSize_writable
#print axioms Whatwg.Streams.Writable.tick_enqueueWrite_error
#print axioms Whatwg.Streams.Writable.tick_enqueueWrite_ok
#print axioms Whatwg.Streams.Writable.tick_advance_busy
#print axioms Whatwg.Streams.Writable.tick_advance_erroring
#print axioms Whatwg.Streams.Writable.tick_advance_empty
#print axioms Whatwg.Streams.Writable.tick_advance_write
#print axioms Whatwg.Streams.Writable.tick_advance_close
#print axioms Whatwg.Streams.Writable.tick_beginClose_rejected
#print axioms Whatwg.Streams.Writable.tick_beginClose_admitted
#print axioms Whatwg.Streams.Writable.tick_beginAbort_terminal
#print axioms Whatwg.Streams.Writable.tick_afterSignal_terminal
#print axioms Whatwg.Streams.Writable.tick_beginAbort_signal
#print axioms Whatwg.Streams.Writable.tick_beginAbort_signaled
#print axioms Whatwg.Streams.Writable.tick_afterSignal_existing
#print axioms Whatwg.Streams.Writable.tick_afterSignal_writable
#print axioms Whatwg.Streams.Writable.tick_afterSignal_erroring
#print axioms Whatwg.Streams.Writable.tick_errorIfNeeded
#print axioms Whatwg.Streams.Writable.tick_controllerError
#print axioms Whatwg.Streams.Writable.tick_startErroring
#print axioms Whatwg.Streams.Writable.tick_dealRejection
#print axioms Whatwg.Streams.Writable.tick_finishErroring
#print axioms Whatwg.Streams.Writable.tick_finishErroring_inFlight
#print axioms Whatwg.Streams.Writable.tick_rejectCloseClosed
#print axioms Whatwg.Streams.Writable.tick_react_unmatched
#print axioms Whatwg.Streams.Writable.tick_write_fulfilled
#print axioms Whatwg.Streams.Writable.tick_write_rejected
#print axioms Whatwg.Streams.Writable.tick_close_fulfilled
#print axioms Whatwg.Streams.Writable.tick_close_rejected
#print axioms Whatwg.Streams.Writable.tick_abort_settled
#print axioms Whatwg.Streams.Writable.step_iff
#print axioms Whatwg.Streams.Writable.reaches_nil
#print axioms Whatwg.Streams.Writable.reaches_cons
#print axioms Whatwg.Streams.Writable.reaches_append_iff
#print axioms Whatwg.Streams.Writable.step_deterministic
#print axioms Whatwg.Streams.Writable.sinkInput_eq
#print axioms Whatwg.Streams.Writable.visibleEvents_eq
#print axioms Whatwg.Streams.Writable.settlementTrace_eq
#print axioms Whatwg.Streams.Writable.observeSink_eq
#print axioms Whatwg.Streams.Writable.observeOrdered_eq
#print axioms Whatwg.Streams.Writable.observeOrdered_toSink
