/-
GENERATED FILE. Do not edit.

Written by `lake exe census --standard infra --write` (`Gates.Census`) from the pinned
`vendor/whatwg-infra-3f984adc/infra.bs` (SHA-256 `7c38e6e25ef21f536142cfc6d94954c41bc9889cd0b6fd67ab34571215acd8eb`), the census projection
`generated/infra-census.tsv`, and the authored disposition inputs under `census/infra/`.
Format version 1. `lake exe census --standard infra` fails on any byte of drift.

This is an all-absent census scaffold, not a checked coverage numerator.
One entry per census row carries its id and joined disposition, with no
theorem witnesses. The census command checks projection drift; the Streams
numerator does not validate this module. `docs/SPEC-COVERAGE.md` owns the rules.
-/

import Gates

namespace WhatwgTest.Audit.Infra.SpecCoverageRows

open Gates.Census

/-- One entry per census row, sorted by kind then id, as the census is. -/
def rows : Array CoverageRow := #[
  ⟨"op.abort-when", .evidenceOnly, .absent, []⟩,
  ⟨"op.allowed", .owned, .absent, []⟩,
  ⟨"op.ascii-alpha", .owned, .absent, []⟩,
  ⟨"op.ascii-alphanumeric", .owned, .absent, []⟩,
  ⟨"op.ascii-byte", .owned, .absent, []⟩,
  ⟨"op.ascii-case-insensitive", .owned, .absent, []⟩,
  ⟨"op.ascii-code-point", .owned, .absent, []⟩,
  ⟨"op.ascii-decode", .owned, .absent, []⟩,
  ⟨"op.ascii-digit", .owned, .absent, []⟩,
  ⟨"op.ascii-encode", .owned, .absent, []⟩,
  ⟨"op.ascii-hex-digit", .owned, .absent, []⟩,
  ⟨"op.ascii-lower-alpha", .owned, .absent, []⟩,
  ⟨"op.ascii-lower-hex-digit", .owned, .absent, []⟩,
  ⟨"op.ascii-lowercase", .owned, .absent, []⟩,
  ⟨"op.ascii-tab-or-newline", .owned, .absent, []⟩,
  ⟨"op.ascii-upper-alpha", .owned, .absent, []⟩,
  ⟨"op.ascii-upper-hex-digit", .owned, .absent, []⟩,
  ⟨"op.ascii-uppercase", .owned, .absent, []⟩,
  ⟨"op.ascii-whitespace", .owned, .absent, []⟩,
  ⟨"op.assert", .evidenceOnly, .absent, []⟩,
  ⟨"op.blocked", .owned, .absent, []⟩,
  ⟨"op.byte-case-insensitive", .owned, .absent, []⟩,
  ⟨"op.byte-less-than", .owned, .absent, []⟩,
  ⟨"op.byte-lowercase", .owned, .absent, []⟩,
  ⟨"op.byte-sequence-length", .owned, .absent, []⟩,
  ⟨"op.byte-sequence-prefix", .owned, .absent, []⟩,
  ⟨"op.byte-sequence-starts-with", .owned, .absent, []⟩,
  ⟨"op.byte-uppercase", .owned, .absent, []⟩,
  ⟨"op.byte-value", .owned, .absent, []⟩,
  ⟨"op.c0-control", .owned, .absent, []⟩,
  ⟨"op.c0-control-or-space", .owned, .absent, []⟩,
  ⟨"op.code-point-substring", .owned, .absent, []⟩,
  ⟨"op.code-point-substring-by-positions", .owned, .absent, []⟩,
  ⟨"op.code-point-substring-to-the-end-of-the-string", .owned, .absent, []⟩,
  ⟨"op.code-point-value", .owned, .absent, []⟩,
  ⟨"op.code-unit-less-than", .owned, .absent, []⟩,
  ⟨"op.code-unit-prefix", .owned, .absent, []⟩,
  ⟨"op.code-unit-substring", .owned, .absent, []⟩,
  ⟨"op.code-unit-substring-by-positions", .owned, .absent, []⟩,
  ⟨"op.code-unit-substring-to-the-end-of-the-string", .owned, .absent, []⟩,
  ⟨"op.code-unit-suffix", .owned, .absent, []⟩,
  ⟨"op.collect-a-sequence-of-code-points", .owned, .absent, []⟩,
  ⟨"op.control", .owned, .absent, []⟩,
  ⟨"op.convert-a-json-derived-java-script-value-to-an-infra-value", .owned, .absent, []⟩,
  ⟨"op.convert-an-infra-value-to-a-json-compatible-java-script-value", .owned, .absent, []⟩,
  ⟨"op.failure", .owned, .absent, []⟩,
  ⟨"op.forgiving-base64-decode", .owned, .absent, []⟩,
  ⟨"op.forgiving-base64-encode", .owned, .absent, []⟩,
  ⟨"op.html-namespace", .owned, .absent, []⟩,
  ⟨"op.if-aborted", .evidenceOnly, .absent, []⟩,
  ⟨"op.implementation", .evidenceOnly, .absent, []⟩,
  ⟨"op.implementation-defined", .evidenceOnly, .absent, []⟩,
  ⟨"op.isomorphic-decode", .owned, .absent, []⟩,
  ⟨"op.isomorphic-encode", .owned, .absent, []⟩,
  ⟨"op.iteration-break", .evidenceOnly, .absent, []⟩,
  ⟨"op.iteration-continue", .evidenceOnly, .absent, []⟩,
  ⟨"op.iteration-while", .evidenceOnly, .absent, []⟩,
  ⟨"op.javascript-string-convert", .owned, .absent, []⟩,
  ⟨"op.leading-surrogate", .owned, .absent, []⟩,
  ⟨"op.list-append", .owned, .absent, []⟩,
  ⟨"op.list-clone", .owned, .absent, []⟩,
  ⟨"op.list-contain", .owned, .absent, []⟩,
  ⟨"op.list-empty", .owned, .absent, []⟩,
  ⟨"op.list-extend", .owned, .absent, []⟩,
  ⟨"op.list-get-the-indices", .owned, .absent, []⟩,
  ⟨"op.list-has-duplicates", .owned, .absent, []⟩,
  ⟨"op.list-insert", .owned, .absent, []⟩,
  ⟨"op.list-is-empty", .owned, .absent, []⟩,
  ⟨"op.list-item", .owned, .absent, []⟩,
  ⟨"op.list-iterate", .owned, .absent, []⟩,
  ⟨"op.list-prepend", .owned, .absent, []⟩,
  ⟨"op.list-remove", .owned, .absent, []⟩,
  ⟨"op.list-replace", .owned, .absent, []⟩,
  ⟨"op.list-reverse", .owned, .absent, []⟩,
  ⟨"op.list-size", .owned, .absent, []⟩,
  ⟨"op.list-slice", .owned, .absent, []⟩,
  ⟨"op.list-sort-in-ascending-order", .requirement, .absent, []⟩,
  ⟨"op.list-sort-in-descending-order", .requirement, .absent, []⟩,
  ⟨"op.map-clear", .owned, .absent, []⟩,
  ⟨"op.map-clone", .owned, .absent, []⟩,
  ⟨"op.map-entry", .owned, .absent, []⟩,
  ⟨"op.map-exists", .owned, .absent, []⟩,
  ⟨"op.map-get", .owned, .absent, []⟩,
  ⟨"op.map-getting-the-keys", .owned, .absent, []⟩,
  ⟨"op.map-getting-the-values", .owned, .absent, []⟩,
  ⟨"op.map-is-empty", .owned, .absent, []⟩,
  ⟨"op.map-iterate", .owned, .absent, []⟩,
  ⟨"op.map-key", .owned, .absent, []⟩,
  ⟨"op.map-remove", .owned, .absent, []⟩,
  ⟨"op.map-set", .owned, .absent, []⟩,
  ⟨"op.map-size", .owned, .absent, []⟩,
  ⟨"op.map-sort-in-ascending-order", .requirement, .absent, []⟩,
  ⟨"op.map-sort-in-descending-order", .requirement, .absent, []⟩,
  ⟨"op.map-value", .owned, .absent, []⟩,
  ⟨"op.map-with-default", .owned, .absent, []⟩,
  ⟨"op.math-ml-namespace", .owned, .absent, []⟩,
  ⟨"op.noncharacter", .owned, .absent, []⟩,
  ⟨"op.normalize-newlines", .owned, .absent, []⟩,
  ⟨"op.parse-a-json-string-to-a-java-script-value", .foreignBoundary, .absent, []⟩,
  ⟨"op.parse-a-json-string-to-an-infra-value", .owned, .absent, []⟩,
  ⟨"op.parse-json-bytes-to-a-java-script-value", .foreignBoundary, .absent, []⟩,
  ⟨"op.parse-json-bytes-to-an-infra-value", .owned, .absent, []⟩,
  ⟨"op.queue-dequeue", .owned, .absent, []⟩,
  ⟨"op.queue-enqueue", .owned, .absent, []⟩,
  ⟨"op.serialize-a-java-script-value-to-a-json-string", .foreignBoundary, .absent, []⟩,
  ⟨"op.serialize-a-java-script-value-to-json-bytes", .foreignBoundary, .absent, []⟩,
  ⟨"op.serialize-an-infra-value-to-a-json-string", .owned, .absent, []⟩,
  ⟨"op.serialize-an-infra-value-to-json-bytes", .owned, .absent, []⟩,
  ⟨"op.set-append", .owned, .absent, []⟩,
  ⟨"op.set-create", .owned, .absent, []⟩,
  ⟨"op.set-difference", .owned, .absent, []⟩,
  ⟨"op.set-equal", .owned, .absent, []⟩,
  ⟨"op.set-extend", .owned, .absent, []⟩,
  ⟨"op.set-intersection", .owned, .absent, []⟩,
  ⟨"op.set-prepend", .owned, .absent, []⟩,
  ⟨"op.set-replace", .owned, .absent, []⟩,
  ⟨"op.set-subset", .owned, .absent, []⟩,
  ⟨"op.set-superset", .owned, .absent, []⟩,
  ⟨"op.set-union", .owned, .absent, []⟩,
  ⟨"op.skip-ascii-whitespace", .owned, .absent, []⟩,
  ⟨"op.split-on-ascii-whitespace", .owned, .absent, []⟩,
  ⟨"op.split-on-commas", .owned, .absent, []⟩,
  ⟨"op.stack-peek", .owned, .absent, []⟩,
  ⟨"op.stack-pop", .owned, .absent, []⟩,
  ⟨"op.stack-push", .owned, .absent, []⟩,
  ⟨"op.strictly-split", .owned, .absent, []⟩,
  ⟨"op.string-code-point-length", .owned, .absent, []⟩,
  ⟨"op.string-concatenate", .owned, .absent, []⟩,
  ⟨"op.string-ends-with", .owned, .absent, []⟩,
  ⟨"op.string-is", .owned, .absent, []⟩,
  ⟨"op.string-length", .owned, .absent, []⟩,
  ⟨"op.string-position-variable", .owned, .absent, []⟩,
  ⟨"op.string-starts-with", .owned, .absent, []⟩,
  ⟨"op.strip-and-collapse-ascii-whitespace", .owned, .absent, []⟩,
  ⟨"op.strip-leading-and-trailing-ascii-whitespace", .owned, .absent, []⟩,
  ⟨"op.strip-newlines", .owned, .absent, []⟩,
  ⟨"op.struct-item", .owned, .absent, []⟩,
  ⟨"op.struct-name", .owned, .absent, []⟩,
  ⟨"op.success", .owned, .absent, []⟩,
  ⟨"op.surrogate", .owned, .absent, []⟩,
  ⟨"op.svg-namespace", .owned, .absent, []⟩,
  ⟨"op.the-exclusive-range", .owned, .absent, []⟩,
  ⟨"op.the-range", .owned, .absent, []⟩,
  ⟨"op.tracking-vector", .evidenceOnly, .absent, []⟩,
  ⟨"op.trailing-surrogate", .owned, .absent, []⟩,
  ⟨"op.user-agent", .evidenceOnly, .absent, []⟩,
  ⟨"op.willful-violation", .evidenceOnly, .absent, []⟩,
  ⟨"op.x-link-namespace", .owned, .absent, []⟩,
  ⟨"op.xml-namespace", .owned, .absent, []⟩,
  ⟨"op.xmlns-namespace", .owned, .absent, []⟩,
  ⟨"type.128-bit-unsigned-integer", .owned, .absent, []⟩,
  ⟨"type.16-bit-signed-integer", .owned, .absent, []⟩,
  ⟨"type.16-bit-unsigned-integer", .owned, .absent, []⟩,
  ⟨"type.32-bit-signed-integer", .owned, .absent, []⟩,
  ⟨"type.32-bit-unsigned-integer", .owned, .absent, []⟩,
  ⟨"type.64-bit-signed-integer", .owned, .absent, []⟩,
  ⟨"type.64-bit-unsigned-integer", .owned, .absent, []⟩,
  ⟨"type.8-bit-signed-integer", .owned, .absent, []⟩,
  ⟨"type.8-bit-unsigned-integer", .owned, .absent, []⟩,
  ⟨"type.ascii-string", .owned, .absent, []⟩,
  ⟨"type.boolean", .owned, .absent, []⟩,
  ⟨"type.byte", .owned, .absent, []⟩,
  ⟨"type.byte-sequence", .owned, .absent, []⟩,
  ⟨"type.code-point", .owned, .absent, []⟩,
  ⟨"type.code-unit", .owned, .absent, []⟩,
  ⟨"type.isomorphic-string", .owned, .absent, []⟩,
  ⟨"type.list", .owned, .absent, []⟩,
  ⟨"type.ordered-map", .owned, .absent, []⟩,
  ⟨"type.ordered-set", .owned, .absent, []⟩,
  ⟨"type.queue", .owned, .absent, []⟩,
  ⟨"type.scalar-value", .owned, .absent, []⟩,
  ⟨"type.scalar-value-string", .owned, .absent, []⟩,
  ⟨"type.stack", .owned, .absent, []⟩,
  ⟨"type.string", .owned, .absent, []⟩,
  ⟨"type.struct", .owned, .absent, []⟩,
  ⟨"type.tuple", .owned, .absent, []⟩
]

/-- Total census rows. -/
def rowTotal : Nat := 176

/-- Rows inside the coverage denominator. -/
def denominator : Nat := 165

end WhatwgTest.Audit.Infra.SpecCoverageRows
